namespace Foxy.Params.SourceGenerator;

partial class ParamsIncrementalGenerator
{
    private static readonly string _generatedCodeAttribute = $@"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{typeof(ParamsIncrementalGenerator).Assembly.GetName().Name}"", ""{typeof(ParamsIncrementalGenerator).Assembly.GetName().Version}"")]";
    private static readonly string _paramsAttribute =
        $$"""
        // <auto-generated/>

        #nullable enable

        namespace Foxy.Params
        {
            {{_generatedCodeAttribute}}
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
            sealed class ParamsAttribute : global::System.Attribute
            {
                public int MaxOverrides { get; set; } = 3;
                public bool HasParams { get; set; } = true;
            }
        }

        """;
}
