using System.Collections.Generic;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;

namespace Foxy.PocoDictionary.SourceGenerator.Helpers;

internal partial class SourceBuilder
{
    private readonly string? _assembly;
    private readonly string? _version;
    private int _intendLevel;

    private readonly StringBuilder _builder = new(2048);

    public SourceBuilder(string intend = "    ",
        string? assembly = null,
        string? version = null)
    {
        Intend = intend;
        
        var assemblyName = Assembly.GetCallingAssembly().GetName();
        _assembly = assembly ?? assemblyName.Name;
        _version = version ?? assemblyName.Version.ToString();
    }

    public string Intend { get; }

    public override string ToString()
    {
        return _builder.ToString();
    }

    public void Field(string type, string name)
    {
        this.AppendLine($"public {type} {name};");
    }

    public void AddAutoGeneratedComment()
    {
        AddLineInternal("// <auto-generated />");
    }

    public void AddNullableEnable()
    {
        AddLineInternal("#nullable enable");
    }

    public void AddGeneratedCodeAttribute()
    {
        AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"{_assembly}\", \"{_version}\")]");
    }

    internal void AppendLine(
        [InterpolatedStringHandlerArgument("")]
        in InterpolatedStringHandler input)
    {
        input.FinishLine();
    }

    public void AppendLine()
    {
        _builder.AppendLine();
    }

    public void AppendTextLine(string text)
    {
        AddIntend();
        _builder.AppendLine(text);
    }

    public SourceLine StartLine()
    {
        return new SourceLine(this);
    }

    public void Clear()
    {
        _intendLevel = 0;
        _builder.Clear();
    }

    private void IncreaseIntend()
    {
        _intendLevel++;
    }

    private void DecreaseIntend()
    {
        _intendLevel--;
    }

    private void AppendInternal(string text)
    {
        _builder.Append(text);
    }

    private void AddLineInternal(string text)
    {
        AddIntend();
        _builder.AppendLine(text);
    }

    private void AddIntend()
    {
        for (int i = 0; i < _intendLevel; i++)
        {
            _builder.Append(Intend);
        }
    }

    private void AddCommaSeparatedList(IEnumerable<string> args)
    {
        _builder.AppendJoin(", ", args);
    }

    private void AppendFormatted<T>(T? t)
    {
        if (t is not null)
        {
            _builder.Append(t.ToString());
        }
    }

    private void Append(string arg)
    {
        _builder.Append(arg);
    }

    private void Append(int arg)
    {
        _builder.Append(arg);
    }

    private void EnsureCapacity(int capacity)
    {
        _builder.EnsureCapacity(capacity);
    }
}
