// <auto-generated />

#nullable enable

namespace Something
{
    partial class Foo
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Foxy.Params.SourceGenerator", "1.0.0.0")]
        public static void Format<T>(string format, T args0)
        {
            var args = new Arguments1<T>(args0);
            var argsSpan = global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref args.arg0, 1);
            Format<T>(format, argsSpan);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Foxy.Params.SourceGenerator", "1.0.0.0")]
        public static void Format<T>(string format, T args0, T args1)
        {
            var args = new Arguments2<T>(args0, args1);
            var argsSpan = global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref args.arg0, 2);
            Format<T>(format, argsSpan);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Foxy.Params.SourceGenerator", "1.0.0.0")]
        public static void Format<T>(string format, params T[] args)
        {
            var argsSpan = new global::System.ReadOnlySpan<T>(args);
            Format<T>(format, argsSpan);
        }
    }

    [global::System.Runtime.CompilerServices.InlineArray(1)]
    file struct Arguments1<T>
    {
        public T arg0;

        public Arguments1(T value0)
        {
            arg0 = value0;
        }
    }

    [global::System.Runtime.CompilerServices.InlineArray(2)]
    file struct Arguments2<T>
    {
        public T arg0;

        public Arguments2(T value0, T value1)
        {
            arg0 = value0;
            this[1] = value1;
        }
    }
}
