// <auto-generated/>

#nullable enable

namespace Foxy.PocoDictionary
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Foxy.PocoDictionary.SourceGenerator", "1.0.0.0")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    sealed class PocoDictionaryAttribute : global::System.Attribute
    {
    }
}
