using Microsoft.CodeAnalysis;

namespace Foxy.PocoDictionary.SourceGenerator;

partial class PocoDictionaryIncrementalGenerator
{
    private static readonly string _generatedCodeAttribute = $@"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{typeof(PocoDictionaryIncrementalGenerator).Assembly.GetName().Name}"", ""{typeof(PocoDictionaryIncrementalGenerator).Assembly.GetName().Version}"")]";
    private static readonly string _pocoDictionarySource =
        $$"""
        // <auto-generated/>

        #nullable enable

        namespace Foxy.PocoDictionary
        {
            {{_generatedCodeAttribute}}
            [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
            sealed class PocoDictionaryAttribute : global::System.Attribute
            {
            }
        }

        """;

    private void AddPocoDictionaryAttribute(IncrementalGeneratorPostInitializationContext context)
    {
        context.AddSource("PocoDictionaryAttribute.g.cs", _pocoDictionarySource);
    }
}
