using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;

namespace SourceGeneratorTools;

/// <summary>
///
/// </summary>
/// <param name="indent">The indent used for indentation.</param>
/// <param name="bufferCapacity">The suggested starting capacitz of the buffer.</param>
public sealed partial class SourceBuilder(string indent = "    ", string? newLine = null, int bufferCapacity = 2048)
{
    private readonly StringBuilder _builder = new(bufferCapacity);
    private int _indentLevel;

    public int IndentLevel => _indentLevel;

    public string Indent { get; } = indent;

    public string NewLine { get; } = Valid(newLine) ?? Environment.NewLine;

    public override string ToString()
    {
        return _builder.ToString();
    }

    public void AddAutoGeneratedComment()
    {
        AppendLineInternal("// <auto-generated />");
    }

    public void AddNullableEnable()
    {
        AppendLineInternal("#nullable enable");
    }

    public void AddGeneratedCodeAttribute(
        string? assembly = null,
        string? version = null)
    {
        var assemblyName = Assembly.GetCallingAssembly().GetName();
        assembly ??= assemblyName.Name;
        version ??= assemblyName.Version.ToString();
        AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"{assembly}\", \"{version}\")]");
    }

    // ReSharper disable once UnusedParameter.Global

    /// <summary>
    /// Starts a scope where you append a continuous line of code in multiple steps.
    /// </summary>
    /// <returns>A <see cref="SourceLine"/> that represents the scope of the line.</returns>
    public SourceLine CreateLine()
    {
        return new SourceLine(this);
    }

    public void Clear()
    {
        _indentLevel = 0;
        _builder.Clear();
    }

    public static implicit operator SourceBuilderSegment(SourceBuilder builder) =>
        new(builder);

    private void IncreaseIndent()
    {
        _indentLevel++;
    }

    private void DecreaseIndent()
    {
        _indentLevel--;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void AppendInternal(string text)
    {
        _builder.Append(text);
    }

    private void AppendLineInternal(string text)
    {
        AddIndent();
        _builder.Append(text);
        AppendNewLine();
    }

    private void AppendNewLine()
    {
        _builder.Append(NewLine);
    }

    private void AddIndent()
    {
        // Stryker disable once update
        for (var i = 0; i < _indentLevel; i++)
        {
            _builder.Append(Indent);
        }
    }

    private void AddCommaSeparatedList<T>(IEnumerable<T> args)
    {
        Helpers.AppendJoin(_builder, ", ", args);
    }

    private void AppendFormatted<T>(T? t)
    {
        _builder.Append(t);
    }

    private void Append(string arg)
    {
        _builder.Append(arg);
    }

    private void Append(int arg)
    {
        _builder.Append(arg);
    }

    // Stryker disable once all
    private void EnsureCapacity(int capacity)
    {
        _builder.EnsureCapacity(capacity);
    }

    private static string? Valid(string? newLine)
    {
        switch (newLine)
        {
            case null:
                return null;
            case "":
                // Stryker disable once string
                throw new ArgumentException("New line cannot be empty.", nameof(newLine));
            case { Length: > 2 }:
                // Stryker disable once string
                throw new ArgumentException("New line cannot be longer than 2 characters.", nameof(newLine));
        }

        return newLine;
    }
}
