using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;

namespace SourceGeneratorTools;

/// <summary>
///
/// </summary>
/// <param name="indent">The indent used for indentation.</param>
/// <param name="bufferCapacity">The suggested starting capacitz of the buffer.</param>
public partial class SourceBuilder(string indent = "    ", int bufferCapacity = 2048)
{
    private int _intendLevel;

    private readonly StringBuilder _builder = new(bufferCapacity);

    public string Indent { get; } = indent;

    public override string ToString()
    {
        return _builder.ToString();
    }

    public void AddAutoGeneratedComment()
    {
        AppendLineInternal("// <auto-generated />");
    }

    public void AddNullableEnable()
    {
        AppendLineInternal("#nullable enable");
    }

    public void AddGeneratedCodeAttribute(
        string? assembly = null,
        string? version = null)
    {
        var assemblyName = Assembly.GetCallingAssembly().GetName();
        assembly ??= assemblyName.Name;
        version ??= assemblyName.Version.ToString();
        AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"{assembly}\", \"{version}\")]");
    }

    // ReSharper disable once UnusedParameter.Global

    /// <summary>
    /// Starts a scope where you append a continuous line of code in multiple steps.
    /// </summary>
    /// <returns>A <see cref="SourceLine"/> that represents the scope of the line.</returns>
    public SourceLine CreateLine()
    {
        return new SourceLine(this);
    }

    public void Clear()
    {
        _intendLevel = 0;
        _builder.Clear();
    }

    private void IncreaseIndent()
    {
        _intendLevel++;
    }

    private void DecreaseIndent()
    {
        _intendLevel--;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void AppendInternal(string text)
    {
        _builder.Append(text);
    }

    private void AppendLineInternal(string text)
    {
        AddIndent();
        _builder.AppendLine(text);
    }

    private void AddIndent()
    {
        for (var i = 0; i < _intendLevel; i++)
        {
            _builder.Append(Indent);
        }
    }

    private void AddCommaSeparatedList<T>(IEnumerable<T> args)
    {
        Helpers.AppendJoin(_builder, ", ", args);
    }

    private void AppendFormatted<T>(T? t)
    {
        if (t is not null)
        {
            _builder.Append(t);
        }
    }

    private void Append(string arg)
    {
        _builder.Append(arg);
    }

    private void Append(int arg)
    {
        _builder.Append(arg);
    }

    private void EnsureCapacity(int capacity)
    {
        _builder.EnsureCapacity(capacity);
    }

    public static implicit operator SourceBuilderSegment(SourceBuilder builder) =>
        new(builder, SourceBuilderSegmentFlags.AddAll);
}
