//HintName: AttributeParsers.g.cs
// <auto-generated />
#nullable enable

public partial class AttributeParsers
{
    public static partial ParsedData ParseData
        (Microsoft.CodeAnalysis.AttributeData attributeData, AttributeParser.Core.AttributeDataParser parser)
    {
        Microsoft.CodeAnalysis.INamedTypeSymbol? __TypeValue = default;
        foreach(var __item in parser.Parse(attributeData))
        {
            switch (__item.GetName())
            {
                case "TypeValue":
                case "typeValue":
                {
                    __TypeValue = __item.GetValue<Microsoft.CodeAnalysis.INamedTypeSymbol?>();
                    break;
                }
                default:
                {
                    throw new ArgumentOutOfRangeException();
                }
            }
        }
        return new ParsedData()
        {
            TypeValue = __TypeValue,
        };
    }
}
