//HintName: AttributeParsers.g.cs
// <auto-generated />
#nullable enable

public partial class AttributeParsers
{
    public static partial ParsedData ParseData
        (Microsoft.CodeAnalysis.AttributeData attributeData, AttributeParser.Core.AttributeDataParser parser)
    {
        System.Collections.Immutable.ImmutableArray<string> __StringArray = default;
        foreach(var __item in parser.Parse(attributeData))
        {
            switch (__item.GetName())
            {
                case "StringArray":
                case "stringArray":
                {
                    __StringArray = __item.GetValues<string>();
                    break;
                }
                default:
                {
                    throw new ArgumentOutOfRangeException();
                }
            }
        }
        return new ParsedData()
        {
            StringArray = __StringArray,
        };
    }
}
