//HintName: AttributeParsers.g.cs
// <auto-generated />
#nullable enable

public partial class AttributeParsers
{
    public static partial ParsedData ParseData
        (Microsoft.CodeAnalysis.AttributeData attributeData, AttributeParser.Core.AttributeDataParser parser)
    {
        System.Collections.Immutable.ImmutableArray<double> __DoubleArray = default;
        foreach(var __item in parser.Parse(attributeData))
        {
            switch (__item.GetName())
            {
                case "DoubleArray":
                case "doubleArray":
                {
                    __DoubleArray = __item.GetValues<double>();
                    break;
                }
                default:
                {
                    throw new ArgumentOutOfRangeException();
                }
            }
        }
        return new ParsedData()
        {
            DoubleArray = __DoubleArray,
        };
    }
}
