//HintName: AttributeParsers.g.cs
// <auto-generated />
#nullable enable

public partial class AttributeParsers
{
    public static partial ParsedData ParseData
        (Microsoft.CodeAnalysis.AttributeData attributeData, AttributeParser.Core.AttributeDataParser parser)
    {
        System.Collections.Immutable.ImmutableArray<EnumValue> __EnumArray = default;
        foreach(var __item in parser.Parse(attributeData))
        {
            switch (__item.GetName())
            {
                case "EnumArray":
                case "enumArray":
                {
                    __EnumArray = __item.GetValues<EnumValue>();
                    break;
                }
                default:
                {
                    throw new ArgumentOutOfRangeException();
                }
            }
        }
        return new ParsedData()
        {
            EnumArray = __EnumArray,
        };
    }
}
