//HintName: AttributeParsers.g.cs
// <auto-generated />
#nullable enable

public partial class AttributeParsers
{
    public static partial ParsedData ParseData
        (Microsoft.CodeAnalysis.AttributeData attributeData, AttributeParser.Core.AttributeDataParser parser)
    {
        string? __StringValue = default;
        foreach(var __item in parser.Parse(attributeData))
        {
            switch (__item.GetName())
            {
                case "StringValue":
                case "stringValue":
                {
                    __StringValue = __item.GetValue<string?>();
                    break;
                }
                default:
                {
                    throw new ArgumentOutOfRangeException();
                }
            }
        }
        return new ParsedData()
        {
            StringValue = __StringValue,
        };
    }
}
