// <auto-generated />

#nullable enable

namespace Something
{
    partial class Foo
    {
        partial class Bar
        {
            [global::System.CodeDom.Compiler.GeneratedCode("Foxy.Params.SourceGenerator", "1.0.0.0")]
            public static void Format(string format, object args0)
            {
                var args = new Arguments1<object>(args0);
                var argsSpan = global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref args.arg0, 1);
                Format(format, argsSpan);
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Foxy.Params.SourceGenerator", "1.0.0.0")]
            public static void Format(string format, object args0, object args1)
            {
                var args = new Arguments2<object>(args0, args1);
                var argsSpan = global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref args.arg0, 2);
                Format(format, argsSpan);
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Foxy.Params.SourceGenerator", "1.0.0.0")]
            public static void Format(string format, object args0, object args1, object args2)
            {
                var args = new Arguments3<object>(args0, args1, args2);
                var argsSpan = global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref args.arg0, 3);
                Format(format, argsSpan);
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Foxy.Params.SourceGenerator", "1.0.0.0")]
            public static void Format(string format, params object[] args)
            {
                var argsSpan = new global::System.ReadOnlySpan<object>(args);
                Format(format, argsSpan);
            }
        }
    }

    [global::System.Runtime.CompilerServices.InlineArray(1)]
    file struct Arguments1<T>
    {
        public T arg0;

        public Arguments1(T value0)
        {
            arg0 = value0;
        }
    }

    [global::System.Runtime.CompilerServices.InlineArray(2)]
    file struct Arguments2<T>
    {
        public T arg0;

        public Arguments2(T value0, T value1)
        {
            arg0 = value0;
            this[1] = value1;
        }
    }

    [global::System.Runtime.CompilerServices.InlineArray(3)]
    file struct Arguments3<T>
    {
        public T arg0;

        public Arguments3(T value0, T value1, T value2)
        {
            arg0 = value0;
            this[1] = value1;
            this[2] = value2;
        }
    }
}
