using System;
using AttributeParser.SourceGenerator.Data;
using Microsoft.CodeAnalysis;
using SourceGeneratorTools;

namespace AttributeParser.SourceGenerator;

public partial class AttributeParserGenerator
{
    private void GenerateSource(SourceProductionContext context, Result result)
    {
        try
        {
            switch (result)
            {
                case ParserClassData data:
                    var builder = new SourceBuilder();
                    BuildSource(builder, data);
                    var hintName = string.IsNullOrWhiteSpace(data.ThisType.Namespace)
                        ? $"{data.ThisType.Name}.g.cs"
                        : $"{data.ThisType.Namespace}.{data.ThisType.Name}.g.cs";
                    context.AddSource(hintName, builder.ToString());
                    break;

                case Error error:
                    string diagnosticMessage = error.Message;
                    var diagnostic = Diagnostic.Create(
                        DiagnosticReports.InternalError,
                        error.Location,
                        diagnosticMessage);
                    context.ReportDiagnostic(diagnostic);
                    break;
            }
        }
        catch (Exception e)
        {
            string diagnosticMessage = $"An unexpected error occurred: {e.Message}";
            Diagnostic diagnostic = Diagnostic.Create(DiagnosticReports.InternalError, null, diagnosticMessage);
            context.ReportDiagnostic(diagnostic);
        }
    }

    private void BuildSource(SourceBuilder builder, ParserClassData data)
    {
        builder.AddAutoGeneratedComment();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        var type = data.ThisType;
        if (!string.IsNullOrWhiteSpace(type.Namespace))
        {
            builder.AppendLine($"namespace {type.Namespace};");
            builder.AppendLine();
        }

        builder.AppendLine($"public partial class {type.Name}");
        using (builder.CreateBlock())
        {
            foreach (var methodData in data.ParserMethods)
            {
                var output = methodData.Output;
                using (var line = builder.CreateLine())
                {
                    line.Append("public");
                    line.Append(" static");
                    line.Append(" partial");
                    line.AppendLine($" {output.FullName} {methodData.MethodName}");
                    var parameters = methodData.SerializeParameters();
                    line.Append($"({parameters})");
                }

                using (builder.CreateBlock())
                {
                    BuildParameterInitialization(builder, output);
                    BuildParameterParsing(builder, methodData);

                    BuildObjectReturnStatement(builder, output);
                }
            }
        }
    }

    private void BuildParameterParsing(SourceBuilder builder, ParserMethodData methodData)
    {
        builder.AppendLine($"foreach(var __item in {methodData.AttributeParser.Name}.Parse({methodData.Attribute.Name}))");
        using (builder.CreateBlock())
        {
            builder.AppendLine("switch (__item.GetName())");
            using (builder.CreateBlock())
            {
                foreach (var parameter in methodData.Output.Parameters)
                {
                    builder.AppendLine($"case \"{parameter.Name}\":");
                    builder.AppendLine($"case \"{parameter.Name.ToCamelCase()}\":");
                    using (builder.CreateBlock())
                    {
                        if (parameter.IsEnumerable)
                        {
                            builder.AppendLine($"__{parameter.Name} = __item.GetValues<{parameter.EnumerableElementType}>();");
                            builder.AppendLine("break;");
                        }
                        else
                        {
                            builder.AppendLine($"__{parameter.Name} = __item.GetValue<{parameter.Type}>();");
                            builder.AppendLine("break;");
                        }
                    }
                }

                builder.AppendLine("default:");
                using (builder.CreateBlock())
                {
                    builder.AppendLine("throw new ArgumentOutOfRangeException();");
                }
            }
        }
    }

    private static void BuildObjectReturnStatement(SourceBuilder builder, ParserMethodOutput output)
    {
        builder.AppendLine($"return new {output.FullName}()");
        using (builder.CreateBlock(closingElement: "};"))
        {
            foreach (var parameter in output.Parameters)
            {
                builder.AppendLine($"{parameter.Name} = __{parameter.Name},");
            }
        }
    }

    private static void BuildParameterInitialization(SourceBuilder builder, ParserMethodOutput output)
    {
        foreach (var parameter in output.Parameters)
        {
            builder.AppendLine($"{parameter.Type} __{parameter.Name} = default;");
        }
    }
}
