// <auto-generated />

#nullable enable

partial class Foo : global::System.Collections.Generic.IReadOnlyDictionary<string, object?>
{
    private static readonly string[] _keys = new string[] { "Bar", "Baz" };

    public int Count => 2;

    public object? this[string key]
    {
        get
        {
            if (TryGetValue(key, out var value))
            {
                return value;
            }

            throw new global::System.Collections.Generic.KeyNotFoundException($"Key {key} not found");
        }
    }

    public global::System.Collections.Generic.IEnumerable<string> Keys => _keys;

    public global::System.Collections.Generic.IEnumerable<object?> Values => new object?[] { Bar, Baz };

    public bool TryGetValue(string key, out object? value)
    {
        switch (key)
        {
            case "Bar":
            {
                value = Bar;
                return true;
            }
            case "Baz":
            {
                value = Baz;
                return true;
            }
            default:
            {
                value = null;
                return false;
            }
        }
    }

    public bool ContainsKey(string key)
    {
        switch (key)
        {
            case "Bar":
            {
                return true;
            }
            case "Baz":
            {
                return true;
            }
            default:
            {
                return false;
            }
        }
    }

    public global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<string, object?>> GetEnumerator()
    {
        yield return new global::System.Collections.Generic.KeyValuePair<string, object?>("Bar", Bar);
        yield return new global::System.Collections.Generic.KeyValuePair<string, object?>("Baz", Baz);
    }

    global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }
}
