using System.Reflection;
using Foxy.Params.SourceGenerator.Helpers;

namespace SourceGeneratorTools.Tests;

public partial class SourceBuilderTests
{
    [Fact]
    public void AddAutoGeneratedComment_AddsAutoGeneratedComment()
    {
        var builder = new SourceBuilder();

        builder.AddAutoGeneratedComment();

        Assert.Content("// <auto-generated />", builder);
    }

    [Fact]
    public void AddNullableEnable_AddsNullableEnableDirective()
    {
        var builder = new SourceBuilder();

        builder.AddNullableEnable();

        Assert.Content("#nullable enable", builder);
    }

    [Fact]
    public void AddGeneratedCodeAttribute_WithoutParameters_AddsGeneratedCodeAttribute()
    {
        var builder = new SourceBuilder();
        var assemblyName = Assembly.GetExecutingAssembly().GetName();
        var assembly = assemblyName.Name;
        var version = assemblyName.Version?.ToString();

        builder.AddGeneratedCodeAttribute();

        Assert.Content($"[global::System.CodeDom.Compiler.GeneratedCode(\"{assembly}\", \"{version}\")]", builder);
    }

    [Fact]
    public void AddGeneratedCodeAttribute_WithParameters_AddsGeneratedCodeAttribute()
    {
        var builder = new SourceBuilder();
        const string assembly = "TestAssembly";
        const string version = "1.0.0";

        builder.AddGeneratedCodeAttribute(assembly, version);

        Assert.Content($"[global::System.CodeDom.Compiler.GeneratedCode(\"{assembly}\", \"{version}\")]", builder);
    }

    [Fact]
    public void Clear_ClearsBuilderContent()
    {
        var builder = new SourceBuilder();
        builder.AppendLine("Some content");

        builder.Clear();

        Assert.Content(string.Empty, builder);
    }

    [Fact]
    public void StartBlock_WithNoParameter_CreatesBlockWithBraces()
    {
        var builder = new SourceBuilder();

        using (builder.StartBlock())
        {
            builder.AppendLine("Inside block");
        }

        Assert.Content(
            """
            {
                Inside block
            }
            """, builder);
    }

    [Fact]
    public void StartBlock_WithParameter_CreatesBlockWithCustomStartAndEnd()
    {
        var builder = new SourceBuilder();

        using (builder.StartBlock("[", "]"))
        {
            builder.AppendLine("Element 1,");
            builder.AppendLine("Element 2");
        }

        Assert.Content(
            """
            [
                Element 1,
                Element 2
            ]
            """, builder);
    }
}
