using SourceGeneratorTools.Tests.TestInfrastructure;

namespace SourceGeneratorTools.Tests;

// ReSharper disable once InconsistentNaming
public class SourceBuilder_Tests
{
    [Test]
    public async Task AddAutoGeneratedComment_AddsAutoGeneratedComment()
    {
        var builder = new SourceBuilder();

        builder.AddAutoGeneratedComment();

        await Assert.That(builder).HasContent("// <auto-generated />");
    }

    [Test]
    public async Task AddNullableEnable_AddsNullableEnableDirective()
    {
        var builder = new SourceBuilder();

        builder.AddNullableEnable();

        await Assert.That(builder).HasContent("#nullable enable");
    }

    [Test]
    public async Task AddGeneratedCodeAttribute_WithoutParameters_AddsGeneratedCodeAttribute()
    {
        var builder = new SourceBuilder();
        var assemblyName = System.Reflection.Assembly.GetExecutingAssembly().GetName();
        var assembly = assemblyName.Name;
        var version = assemblyName.Version?.ToString();

        builder.AddGeneratedCodeAttribute();

        await Assert.That(builder).HasContent($"[global::System.CodeDom.Compiler.GeneratedCode(\"{assembly}\", \"{version}\")]");
    }

    [Test]
    public async Task AddGeneratedCodeAttribute_WithParameters_AddsGeneratedCodeAttribute()
    {
        var builder = new SourceBuilder();
        const string assembly = "TestAssembly";
        const string version = "1.0.0";

        builder.AddGeneratedCodeAttribute(assembly, version);

        await Assert.That(builder).HasContent($"[global::System.CodeDom.Compiler.GeneratedCode(\"{assembly}\", \"{version}\")]");
    }

    [Test]
    public async Task Clear_ClearsBuilderContent()
    {
        var builder = new SourceBuilder();
        builder.AppendLine("Some content");

        builder.Clear();

        await Assert.That(builder).HasContent(string.Empty);
    }
}
