// <auto-generated />

#nullable enable

namespace Something
{
    partial class Foo
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Foxy.Params.SourceGenerator", "1.0.0.0")]
        public static void Format(string format, string values0)
        {
            var values = new Arguments1<string>(values0);
            var valuesSpan = global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref values.arg0, 1);
            Format(format, valuesSpan);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Foxy.Params.SourceGenerator", "1.0.0.0")]
        public static void Format(string format, string values0, string values1)
        {
            var values = new Arguments2<string>(values0, values1);
            var valuesSpan = global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref values.arg0, 2);
            Format(format, valuesSpan);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Foxy.Params.SourceGenerator", "1.0.0.0")]
        public static void Format(string format, params string[] values)
        {
            var valuesSpan = new global::System.ReadOnlySpan<string>(values);
            Format(format, valuesSpan);
        }
    }

    [global::System.Runtime.CompilerServices.InlineArray(1)]
    file struct Arguments1<T>
    {
        public T arg0;

        public Arguments1(T value0)
        {
            arg0 = value0;
        }
    }

    [global::System.Runtime.CompilerServices.InlineArray(2)]
    file struct Arguments2<T>
    {
        public T arg0;

        public Arguments2(T value0, T value1)
        {
            arg0 = value0;
            this[1] = value1;
        }
    }
}
